# Generated by Django 5.0.4 on 2024-04-24 07:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_accountuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
